redditclone/reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index]

end

redditclone/reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

redditclone/reddit_clone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  validates :
end

redditclone/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  validates :subs, presence: { message: 'must have at least one sub'}

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'User'

  has_many :post_subs,
    inverse_of: :post,
    dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub
end

redditclone/reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: 'Post'

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: 'Sub'

end

redditclone/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: 'User'

  has_many :post_subs,
    inverse_of: :sub,
    dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post


end

redditclone/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password

  after_initialize :ensure_session_token!
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }


  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: 'Sub'

  has_many :posts,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'Post'


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    if @user && @user.is_password?(password)
      return @user
    end
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end


  private
  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

redditclone/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in!(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def signed_in?
    !!current_user
  end

  def sign_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless current_user
  end

end

redditclone/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save!
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id, sub_ids: [])
  end
end

redditclone/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )
    if @user
      sign_in!(@user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

end

redditclone/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in!

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

redditclone/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

redditclone/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

redditclone/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

redditclone/reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

redditclone/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

redditclone/reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

redditclone/reddit_clone/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

redditclone/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if signed_in? %>
      <%= current_user.username %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
      <br>
    <% else %>
      <%= link_to 'Sign In', new_session_url %>
      <%= link_to 'Sign Up', new_user_url %>
      <br>
    <% end %>

    <%= render 'layouts/errors' %>

    <%= yield %>
  </body>
</html>

redditclone/reddit_clone/app/views/posts/_form.html.erb
<!DOCTYPE html>

<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%=action_url%>" method="POST">
  <%= auth_token_input %>
    <input type="hidden" name="_method" value="<%=http_method%>">

  <label>
    Title
    <input type="text" name="post[title]" value="<%=post.title%>">
  </label>
  <br>
  <br>

  <label>
    URL
    <input type="text" name="post[url]" value="<%=post.url%>">
  </label>
  <br>
  <br>

  <label>
    Content
    <textarea type="text" name="post[content]" value="<%=post.content%>"></textarea>
  </label>
  <br>


  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |subb| %>
    <label>
      <input
      type="checkbox"
      name="post[sub_ids][]"
      value= "<%=subb.id%>"
      <%= "checked" if post.sub_ids.include?(subb.id) %>>
      <%= subb.title %>
    </label>
    <br>
  <% end %>

  <br>
  <input type="submit" value="Post">
</form>

redditclone/reddit_clone/app/views/posts/edit.html.erb
<!DOCTYPE html>

<h1>Edit Post</h1>

<%= render "form", post: @post %>

redditclone/reddit_clone/app/views/posts/new.html.erb
<!DOCTYPE html>

<h1>Add Post</h1>

<%= render "form", post: @post %>

redditclone/reddit_clone/app/views/posts/show.html.erb
<!DOCTYPE html>

Title: <%= @post.title %>
URL: <%= @post.url %>
<br>
<%= @post.content %>

redditclone/reddit_clone/app/views/subs/_form.html.erb
<!DOCTYPE html>

<% action_url = sub.persisted? ? sub_url(@sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>

<form action= "<%=action_url%>" method= "<%=http_method%>" >
  <%= auth_token_input %>

  <label>
    Title
    <input type="text" name="sub[title]" value= "<%=sub.title%>" >
  </label>

  <label>
    Description
    <input type="text" name="sub[description]" value= "<%=sub.description%>">
  </label>

  <input type="submit" value="Create Sub">
</form>

redditclone/reddit_clone/app/views/subs/edit.html.erb
<!DOCTYPE html>

<h1>Edit Sub</h1>

<form action= "<%=sub_url(@sub)%>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="sub[title]" value= "<%=@sub.title%>" >
  </label>

  <label>
    Description
    <input type="text" name="sub[description]" value= "<%=@sub.description%>" >
  </label>

  <input type="submit" value="Update Sub">
</form>

redditclone/reddit_clone/app/views/subs/index.html.erb
<!DOCTYPE html>

<h1>Subs</h1>

<ul>
  <% @subs.each do |subb| %>
    <li>
      <%= link_to subb.title, sub_url(subb) %>
    </li>
    <br>
  <% end %>
</ul>

<%= link_to 'New Sub', new_sub_url %>

redditclone/reddit_clone/app/views/subs/new.html.erb
<!DOCTYPE html>

<h1>New Sub</h1>

<form action= "<%=subs_url%>" method="post">
  <%= auth_token_input %>

  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label>
    Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" value="Create Sub">
</form>

redditclone/reddit_clone/app/views/subs/show.html.erb
<!DOCTYPE html>

Title: <%= @sub.title %>
<br>
Description: <%= @sub.description %>
<br>
Moderator: <%= @sub.moderator.username %>
<br>

<h1>Posts</h1>

<ul>
  <% @sub.posts.each do |post| %>
    <li>
    Title: <%= post.title %>
    Author: <%= post.author.username %>
    URL: <%= post.url %>
    <%= post.content %>
    <br>
    </li>
  <% end %>
</ul>
</form>

redditclone/reddit_clone/app/views/users/index.html.erb
<!DOCTYPE html>

<h1>Users</h1>

<ul>

  <% @users.each do |user| %>
    <li>
    <%= user.username %>
    <ul>
      <% user.subs.each do |subb| %>
        <li> <%= link_to subb.title, sub_url(subb) %> </li>
      <% end %>
    </ul>
    </li>

    <br>
  <% end %>

</ul>

redditclone/reddit_clone/app/views/users/new.html.erb
<!DOCTYPE html>

<h1>Sign Up</h1>

<form action= "<%=users_url%>" method="post">
  <%= auth_token_input %>

  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>